//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenNETCF.ORM
{
    using System;
    using OpenNETCF.ORM;
    
    
    [Entity(KeyScheme.None)]
    public class TestTable
    {
        
        private static TestTable ORM_CreateProxy(OpenNETCF.ORM.FieldAttributeCollection fields, System.Data.IDataReader results)
        {
            var item = new TestTable();
foreach(var field in fields){
            var value = results[field.Ordinal];
switch(field.FieldName){
case "Description":
            item.Description = (value == DBNull.Value) ? null : (string)value;
            break;
}
}
            return item;
        }
        
        private string m_description;
        
        [Field()]
        public string Description
        {
            get
            {
                return this.m_description;
            }
            set
            {
                this.m_description = value;
            }
        }
    }
}
