//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFL.Core.DAL.DAO
{
    using System;
    using OpenNETCF.ORM;
    
    
   // [Entity(KeyScheme.None)]
	[Entity(KeyScheme.Identity)]
    public class PerfTestResults
    {
        
        private int m_id;
        
        private string m_databasefile;
        
        private string m_databaseproduct;
        
        private string m_tablename;
        
        private string m_begintimestamp;
        
        private string m_sqloperation;
        
        private string m_description;
        
        private string m_elapsedtime;
        
        private int m_numrowsaffected;
        
        private string m_endtimestamp;
        
        private int m_seqnum;

    	private string _providerClass;
        
        [Field(IsPrimaryKey=true, SearchOrder=FieldSearchOrder.Ascending)]
        public int Id
        {
            get
            {
                return this.m_id;
            }
            set
            {
                this.m_id = value;
            }
        }
        
        [Field()]
        public string DatabaseFile
        {
            get
            {
                return this.m_databasefile;
            }
            set
            {
                this.m_databasefile = value;
            }
        }
        
        [Field()]
        public string DatabaseProduct
        {
            get
            {
                return this.m_databaseproduct;
            }
            set
            {
                this.m_databaseproduct = value;
            }
        }
        
        [Field()]
        public string TableName
        {
            get
            {
                return this.m_tablename;
            }
            set
            {
                this.m_tablename = value;
            }
        }
        
        [Field()]
        public string BeginTimeStamp
        {
            get
            {
                return this.m_begintimestamp;
            }
            set
            {
                this.m_begintimestamp = value;
            }
        }
        
        [Field()]
        public string SqlOperation
        {
            get
            {
                return this.m_sqloperation;
            }
            set
            {
                this.m_sqloperation = value;
            }
        }
        
        [Field()]
        public string Description
        {
            get
            {
                return this.m_description;
            }
            set
            {
                this.m_description = value;
            }
        }
        
        [Field()]
        public string ElapsedTime
        {
            get
            {
                return this.m_elapsedtime;
            }
            set
            {
                this.m_elapsedtime = value;
            }
        }
        
        [Field()]
        public int NumRowsAffected
        {
            get
            {
                return this.m_numrowsaffected;
            }
            set
            {
                this.m_numrowsaffected = value;
            }
        }
        
        [Field()]
        public string EndTimeStamp
        {
            get
            {
                return this.m_endtimestamp;
            }
            set
            {
                this.m_endtimestamp = value;
            }
        }
        
        [Field()]
        public int SeqNum
        {
            get
            {
                return this.m_seqnum;
            }
            set
            {
                this.m_seqnum = value;
            }
        }

    	public string ProviderClass
    	{
    		get { return _providerClass; }
    		set { _providerClass = value; }
    	}
    }
}
